const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const projects=window.BBJ.projects;
const projectLink=q=>'project.html?id='+encodeURIComponent(q.id);
const grid=document.querySelector('.archive .grid');if(grid){grid.innerHTML=projects.map(q=>`<li class="project" data-category="${esc(q.category)}"><a href="${projectLink(q)}" aria-label="Open ${esc(q.title)}"><div class="thumb"><img class="base" src="${esc(q.drawing)}" alt="${esc(q.title)} drawing" loading="lazy">${q.render?`<img class="alternate" src="${esc(q.render)}" alt="" loading="lazy">`:''}</div><span class="project-number">${esc(q.id)}</span><span class="project-title">${esc(q.title)} / ${esc(q.category)}</span></a></li>`).join('');document.querySelector('.archive-bar h1 span').textContent=String(projects.length).padStart(2,'0')+' studies';}
const projectPage=document.querySelector('.project-page');if(projectPage){const id=new URLSearchParams(location.search).get('id')||location.pathname.match(/project-([^/]+)\.html$/)?.[1]||projects[0]?.id;const q=projects.find(q=>q.id===id);if(!q){projectPage.innerHTML='<h1>Study not found.</h1><a class="text-link" href="index.html">Return to archive →</a>';document.title='Study not found — BBJ';}else{document.title=q.title+' — BBJ';const n=projects.indexOf(q),prev=projects[(n-1+projects.length)%projects.length],next=projects[(n+1)%projects.length];const figure=(src,label)=>`<figure class="project-hero"><button class="image-open" data-image="${esc(src)}" data-caption="${esc(q.title+' / '+label)}" aria-label="Enlarge ${esc(label)}"><img src="${esc(src)}" alt="${esc(q.title+' / '+label)}" loading="lazy"></button><figcaption>${esc(q.id+' / '+label)}</figcaption></figure>`;projectPage.innerHTML=`<div class="project-intro"><div><p class="eyebrow">BBJ / SELECTED STUDIES</p><h1>${esc(q.id)}<span>${esc(q.title)}</span></h1></div><div><p>${esc(q.description)}</p><dl class="metadata">${[['Category',q.category],['Location',q.location],['Year',q.year],['Status',q.status],['Credits',q.credits]].filter(pair=>pair[1]).map(pair=>`<dt>${esc(pair[0])}</dt><dd>${esc(pair[1])}</dd>`).join('')}</dl></div></div>${figure(q.drawing,'Drawing')}${q.render?`<section class="compare" aria-label="Drawing and image comparison"><img src="${esc(q.render)}" alt="${esc(q.title)} image"><div class="compare-overlay"><img src="${esc(q.drawing)}" alt="${esc(q.title)} drawing"></div><label>Drawing <input type="range" min="0" max="100" value="50" aria-label="Reveal drawing over image"> Image</label></section>${figure(q.render,'Image')}`:''}${(q.gallery||[]).map(item=>figure(item.src,item.caption||'Detail')).join('')}<nav class="project-nav" aria-label="Project navigation"><a href="${projectLink(prev)}">← ${esc(prev.id)}</a><a href="index.html">All studies</a><a href="${projectLink(next)}">${esc(next.id)} →</a></nav>`;}}
const archive=document.querySelector('.archive');document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{archive.classList.toggle('pictorial',button.dataset.view==='pictorial');archive.classList.toggle('list-view',button.dataset.view==='list');document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));
const viewer=document.querySelector('#viewer');document.querySelectorAll('[data-image]').forEach(button=>button.addEventListener('click',()=>{viewer.querySelector('img').src=button.dataset.image;viewer.querySelector('img').alt=button.dataset.caption;viewer.querySelector('p').textContent=button.dataset.caption;viewer.showModal();}));viewer.querySelector('.close').addEventListener('click',()=>viewer.close());viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});
document.querySelectorAll('.compare input').forEach(input=>input.addEventListener('input',()=>{input.closest('.compare').querySelector('.compare-overlay').style.clipPath=`inset(0 ${100-input.value}% 0 0)`}));
const form=document.querySelector('#contact-form');if(form){const email=window.BBJ.profile.email;const channel=document.querySelector('#contact-channel');if(email){channel.textContent='';const a=document.createElement('a');a.href='mailto:'+email;a.textContent=email;channel.append(a);form.querySelector('button').textContent='Open email enquiry ↗';form.querySelector('.small').textContent='Opens your email application. No information is stored by this website.'}form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const body=`Name: ${d.get('name')}
Email: ${d.get('email')}
Subject: ${d.get('subject')}

${d.get('message')}`;if(email){location.href=`mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent('BBJ / '+d.get('subject'))}&body=${encodeURIComponent(body)}`;document.querySelector('#form-status').textContent='Your email application will open. Review and send your message there.'}else{const url=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='BBJ-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#form-status').textContent='Enquiry file prepared. It has not been sent.'}})}
const infoTabs=[...document.querySelectorAll('[data-info]')];
const infoStates={drawing:{src:'096-drawing.jpg',title:'Thinking through a line.',copy:'Drawings make room to observe, test and develop an idea.',caption:'Drawing / supplied sample'},space:{src:'about-image.jpg',title:'Reading a space.',copy:'Explore scale, atmosphere and the relationships within a place.',caption:'Space / supplied sample'},image:{src:'096-render.jpg',title:'An idea, made visible.',copy:'Move from the drawing to an image and see another perspective.',caption:'Image / supplied sample'}};
function selectInfo(tab){const state=infoStates[tab.dataset.info];infoTabs.forEach(t=>{t.setAttribute('aria-selected',String(t===tab));t.tabIndex=t===tab?0:-1});const panel=document.querySelector('#info-panel');panel.setAttribute('aria-labelledby',tab.id);const img=document.querySelector('#info-study');img.src=state.src;img.alt=state.caption;document.querySelector('#info-study-title').textContent=state.title;document.querySelector('#info-study-copy').textContent=state.copy;const open=panel.querySelector('[data-image]');open.dataset.image=state.src;open.dataset.caption=state.caption;}
infoTabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectInfo(tab));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(i+1)%infoTabs.length;if(event.key==='ArrowLeft')next=(i+infoTabs.length-1)%infoTabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=infoTabs.length-1;if(next!==undefined){event.preventDefault();infoTabs[next].focus();selectInfo(infoTabs[next])}})});
